version: '3'
services:
  nextcloud:
    image: nextcloud:stable
    restart: always
    ports:
      - 8008:80
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=nxcAdmin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=redis
    networks:
      - openldap
networks:
  openldap:
    external: true