version: '2'
services:
  moodle:
    image: bitnami/moodle:latest
    env_file:
      - moodle.env
    ports:
      - 80:8080
      - 443:8443      
    volumes:
      - ./moodle_data:/bitnami/moodle
      - ./moodledata_data:/bitnami/moodledata
    hostname: moodle.local
    networks:
      - openldap  
  
networks:
  openldap:
    external: true