version: '3'
services:
  moodle:
    image: bitnami/moodle:latest
    environment:
      - EXTRA_LOCALES=fr_FR.UTF-8 UTF-8, de_DE.UTF-8 UTF-8, it_IT.UTF-8 UTF-8, es_ES.UTF-8 UTF-8
      - MOODLE_DATABASE_HOST=db
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle
      - PHP_ENABLE_OPCACHE=true
      - PHP_MEMORY_LIMI=512M
    ports:
      - 80:8080
      - 443:8443      
    volumes:
      - ./moodle_data/moodle:/bitnami/moodle
      - ./moodle_data/data:/bitnami/moodledata
    hostname: moodle
    networks:
      - openldap  
  
networks:
  openldap:
    external: true