version: '3.1'

services:
  db:
    image: mariadb:lts
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - openldap

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    hostname: phpmyadmin
    ports:
      - '8081:80'
    networks:
      - openldap
networks:
  openldap:
    external: true