version: '3.1'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql:Z
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - openldap

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - openldap
networks:
  openldap:
    external: true