version: '3.8'
services:
  redis:
    image: redis:7.2.3-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes: 
      - ./cache:/data
    networks:
      - openldap
networks:
  openldap:
    external: true